### ISSUE TITLE
LDAPS implementation

### ISSUE THREAD

**Issue by kuhball** [sismics/docs#517]
Thanks for developing this awesome product & implementing LDAP. 

I have no experience in java but would it be possible to provide the option to use encrypted LDAP Connections via TLS / SSL from the admin webinterface? Normally the certificate is provided by an ENV Variable (LDAPTLS_CACERT) within the Dockercontainer.

**Comment by bhotrock** [comment]
I agree with kuhball.  We need to be able to connect to an LDAP server in another datacenter.  At this point, I would need to setup a VPN for security purposes.

**Comment by wolicape** [comment]
Hi, any news about it ? Does LDAPS works in the last release ? I tried to import our CA in cacerts keystore, configure LDAP to use port 636 (our LDAPS port) but it doesn't work actually. I don't know how to configure it if it's already integrated, I would be grateful for a feedback 🙏

**Comment by jendib** [comment]
The issue is still opened and nobody worked on it

**Comment by nemhods** [comment]
Hey, so I could take a jab at this, since essentially all that's required would be a `config.setUseSSL(true)` [here](https://github.com/sismics/docs/blob/c6a685d7c04ce6c3d632016240648142ec46d956/docs-core/src/main/java/com/sismics/docs/core/util/authentication/LdapAuthenticationHandler.java#L69).

The thing that worries me is that I have no clue how to navigate all the other boilerplate code around creating a new setting, surfacing it in the UI, changing all enums, API calls and tests to support it.
Is it okay for this project to just give it a try? Or do you prefer this to be done by someone with basic understanding of the codebase @jendib ?

**Comment by jendib** [comment]
@nemhods Definitely go ahead and create a draft PR, I can assist you if you need to understand anything.

**Comment by vmario89** [comment]
implemented that feature with the satanic pull request number 666: https://github.com/sismics/docs/pull/666

**Comment by vmario89** [comment]
made a new PR at https://github.com/sismics/docs/pull/670

**Comment by jendib** [comment]
Thanks!
