### ISSUE TITLE
Issue processing .txt files

### ISSUE THREAD

**Issue by techstack2022** [sismics/docs#629]
Hi,

I imported few text files (.txt) and observed the following

#1 - Preview of .txt file is not working
#2 - When clicked to view the .txt file, nothing is displaying except blank window (https://demo.teedy.io/api/file/27bfd019-5fb6-4133-90e2-727b1cb629fe/data?size=content)
#3 - Number of matches found is not displayed while typing and it displayed only after hitting search

Thanks

**Comment by jendib** [comment]
@jdtimmerman This might be related to your recent contribution in MimeTypeUtil.java, would you have time to take a look? Thanks.

**Comment by jendib** [comment]
Apparently there is 2 issues here:
- An error caused by https://bugs.openjdk.java.net/browse/JDK-6986863 and fixed very recently in openjdk 11.0.16. I will upgrade Teedy when this version in packaged for Ubuntu
- Your .txt files are not in UTF-8 encoding. Could you attach one of your files here? Thanks

**Comment by jendib** [comment]
Waiting for openjdk 11.0.16 as Ubuntu package

**Comment by jendib** [comment]
Upgraded to 11.0.18
