### ISSUE TITLE
How to export all documents?

### ISSUE THREAD

**Issue by cyberfreakde** [sismics/docs#660]
So I have stored a huge amount of documents in teedy now but I would like to export it all for backups. How is it possible?

**Comment by vmario89** [comment]
i made some docs for this, still using them and it still works. https://stadtfabrikanten.org/display/TEED/Teedy+1.9+Backup+and+restore+strategies

**Comment by vmario89** [comment]
[TEED-Teedy1.12Backupandrestorestrategies-010524-1809-2.pdf](https://github.com/sismics/docs/files/15178902/TEED-Teedy1.12Backupandrestorestrategies-010524-1809-2.pdf)

hi please inspect that doc. our server was hacked last year. due to lack of time i was not able to republish all documentation things yet.
